server.port=5454
spring.application.name=OnlineFoodOrdering

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/onlinefood
spring.datasource.username=root
spring.datasource.password=Moni#123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

